export const questions = [
    { text: 'What is the capital of France?', answer: 'Paris' },
    { text: 'What is the largest planet in our Solar System?', answer: 'Jupiter' },
    { text: 'What is the square root of 81?', answer: '9' },
    { text: 'Who wrote "Romeo and Juliet"?', answer: 'William Shakespeare' },
    { text: 'What is the chemical symbol for water?', answer: 'H2O' },
    { text: 'How many continents are there on Earth?', answer: '7' },
    { text: 'What is the fastest land animal?', answer: 'Cheetah' },
    { text: 'What year did the Titanic sink?', answer: '1912' },
    { text: 'What is the smallest prime number?', answer: '2' },
    { text: 'What is the name of the fairy in Peter Pan?', answer: 'Tinker Bell' },
    { text: 'Who painted the Mona Lisa?', answer: 'Leonardo da Vinci' },
    { text: 'What is the capital of Italy?', answer: 'Rome' },
    { text: 'What is the largest country by area?', answer: 'Russia' },
    { text: 'What is the freezing point of water in degrees Celsius?', answer: '0' },
    { text: 'What is the powerhouse of the cell?', answer: 'Mitochondria' },
    { text: 'How many sides does a hexagon have?', answer: '6' },
    { text: 'Who is known as the father of computer science?', answer: 'Alan Turing' },
    { text: 'What does the Internet prefix WWW stand for?', answer: 'World Wide Web' },
    { text: "What element does 'O' represent on the periodic table?", answer: 'Oxygen' },
    { text: 'What is the term for a word that is similar in meaning to another word?', answer: 'Synonym' },
];